{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "outputs": [],
   "source": [
    "import cv2\n",
    "import itertools\n",
    "import numpy as np\n",
    "import re\n",
    "import glob\n",
    "import os\n",
    "import pickle\n",
    "import json\n",
    "from skimage import transform as transf\n",
    "import concurrent.futures\n",
    "from tqdm import tqdm"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "outputs": [],
   "source": [
    "lips_folder = '/home/taylorpap/Bootcamp/lips_points'"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "outputs": [],
   "source": [
    "def save2npz(filename, data=None):\n",
    "    if not os.path.exists(os.path.dirname(filename)):\n",
    "        os.makedirs(os.path.dirname(filename))\n",
    "    np.savez_compressed(filename, data=data)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "outputs": [],
   "source": [
    "#Linear Interpolate on images/frames that are missing landmarks\n",
    "def linear_interpolate(landmarks, start_idx, stop_idx):\n",
    "    start_landmarks = landmarks[start_idx]\n",
    "    stop_landmarks = landmarks[stop_idx]\n",
    "    delta = stop_landmarks - start_landmarks\n",
    "    for idx in range(1, stop_idx-start_idx):\n",
    "        landmarks[start_idx+idx] = start_landmarks + idx/float(stop_idx-start_idx) * delta\n",
    "    return landmarks"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "outputs": [],
   "source": [
    "def interpolate_missing_landmarks(landmarks):\n",
    "    good_frames = [indexes for indexes, _ in enumerate(landmarks) if _ is not None]\n",
    "    if not good_frames:\n",
    "        return None\n",
    "    for idx in range(1, len(good_frames)):\n",
    "        if good_frames[idx] - good_frames[idx-1] == 1:\n",
    "            continue\n",
    "        else:\n",
    "            landmarks = linear_interpolate(landmarks, good_frames[idx-1], good_frames[idx])\n",
    "    valid_frames_idx = [idx for idx, _ in enumerate(landmarks) if _ is not None]\n",
    "    # -- Corner case: keep frames at the beginning or at the end failed to be detected.\n",
    "    if valid_frames_idx:\n",
    "        landmarks[:valid_frames_idx[0]] = [landmarks[valid_frames_idx[0]]] * valid_frames_idx[0]\n",
    "        landmarks[valid_frames_idx[-1]:] = [landmarks[valid_frames_idx[-1]]] * (len(landmarks) - valid_frames_idx[-1])\n",
    "    return landmarks"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "outputs": [],
   "source": [
    "#Create Method for warping image and getting transform parameters\n",
    "def warp_img(src, dst, img, std_size):\n",
    "    tform = transf.estimate_transform('similarity', src, dst)  # find the transformation matrix\n",
    "    warped = transf.warp(img, inverse_map=tform.inverse, output_shape=std_size)  # wrap the frame image\n",
    "    warped = warped * 255  # note output from wrap is double image (value range [0,1])\n",
    "    warped = warped.astype('uint8')\n",
    "    return warped, tform\n",
    "#Create Method to apply a previously calculated transform\n",
    "def apply_transform(transform, img, std_size):\n",
    "    warped = transf.warp(img, inverse_map=transform.inverse, output_shape=std_size)\n",
    "    warped = warped * 255  # note output from wrap is double image (value range [0,1])\n",
    "    warped = warped.astype('uint8')\n",
    "    return warped"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "outputs": [],
   "source": [
    "def crop_out_patch(img, landmarks, height, width):\n",
    "    center_x, center_y = np.mean(landmarks, axis=0)\n",
    "\n",
    "    cutted_img = np.copy(img[int(round(center_y) - round(height)): int(round(center_y) + round(height)),\n",
    "                         int(round(center_x) - round(width)): int(round(center_x) + round(width))])\n",
    "    return cutted_img"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "outputs": [],
   "source": [
    "test_none = [{'testnone': np.array([[0.28191882, 0.53480649],\n",
    "        [0.75067544, 0.33600596]])},{'testnone': np.array([None])},{'testnone': np.array([[0.28191882, 0.53480649],\n",
    "        [0.75067544, 0.33600596]])}]"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "outputs": [],
   "source": [
    "face_oval_avgs = np.load('/home/taylorpap/Bootcamp/face_oval_averages.npz', allow_pickle=True)['data']\n",
    "face_oval_avgs = face_oval_avgs * 256\n",
    "std_size = (256, 256)\n",
    "landmark_indexes_for_cropping = [2, 3, 10, 11, 26, 30]"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "outputs": [],
   "source": [
    "def crop_and_return_lip_landmarks(video_path, output_path, oval_landmarks, mouth_landmarks):\n",
    "    vid_capture = cv2.VideoCapture(video_path)\n",
    "    frame_idx = 0\n",
    "    crop_width = 96\n",
    "    crop_height = 96\n",
    "    cropped_size = (crop_width, crop_height)\n",
    "    lips_points = []\n",
    "    if (vid_capture.isOpened() == False):\n",
    "        print(\"Error opening the video file\")\n",
    "    else:\n",
    "        fps = int(vid_capture.get(5))\n",
    "\n",
    "        #output_video = cv2.VideoWriter(output_path, cv2.VideoWriter_fourcc('m', 'p', '4', 'v'), fps, cropped_size)\n",
    "        while(vid_capture.isOpened()):\n",
    "            ret, frame = vid_capture.read()\n",
    "            if ret:\n",
    "                current_oval = oval_landmarks[frame_idx] *256\n",
    "                current_lips = mouth_landmarks[frame_idx] *256\n",
    "                if frame_idx == 0:\n",
    "                    transformed_frame, trans_mat = warp_img(current_oval[landmark_indexes_for_cropping, :],\n",
    "                                                            face_oval_avgs[landmark_indexes_for_cropping, :],\n",
    "                                                            frame,\n",
    "                                                            std_size)\n",
    "                    sequence = []\n",
    "                trans_lips = trans_mat(current_lips)\n",
    "                trans_frame = apply_transform(trans_mat, frame, std_size)\n",
    "                cut_frame = crop_out_patch(trans_frame, trans_lips, crop_height//2, crop_width//2)\n",
    "                #output_video.write(cut_frame)\n",
    "                sequence.append(cut_frame)\n",
    "                lips_points.append(trans_lips)\n",
    "                frame_idx+= 1\n",
    "            else:\n",
    "                break\n",
    "    vid_capture.release()\n",
    "    #output_video.release()\n",
    "    cv2.destroyAllWindows()\n",
    "    return np.array(lips_points), np.array(sequence)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[array([[0.28191882, 0.53480649],\n",
      "       [0.75067544, 0.33600596]]), array([None], dtype=object), array([[0.28191882, 0.53480649],\n",
      "       [0.75067544, 0.33600596]])]\n"
     ]
    }
   ],
   "source": [
    "landmarks = [None] * len(test_none)\n",
    "for frame_idx in range(len(landmarks)):\n",
    "    try:\n",
    "        landmarks[frame_idx] = test_none[frame_idx]['testnone']\n",
    "    except IndexError:\n",
    "        continue\n",
    "test_landmarks = interpolate_missing_landmarks(landmarks)\n",
    "print(test_landmarks)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "outputs": [],
   "source": [
    "def interpolate_oval_and_face(landmarks_npz):\n",
    "    landmarks_data = np.load(landmarks_npz, allow_pickle=True)['data']\n",
    "    landmarks_ovals = [None] * len(landmarks_data)\n",
    "    landmarks_lips = [None] * len(landmarks_data)\n",
    "    for frame_idx in range(len(landmarks_ovals)):\n",
    "        try:\n",
    "            landmarks_ovals[frame_idx] = landmarks_data[frame_idx]['oval_landmarks']\n",
    "        except IndexError:\n",
    "            continue\n",
    "    for frame_idx in range(len(landmarks_lips)):\n",
    "        try:\n",
    "            landmarks_lips[frame_idx] = landmarks_data[frame_idx]['lips_landmarks']\n",
    "        except IndexError:\n",
    "            continue\n",
    "    preprocessed_ovals = interpolate_missing_landmarks(landmarks_ovals)\n",
    "    preprocessed_lips = interpolate_missing_landmarks(landmarks_lips)\n",
    "    return preprocessed_ovals, preprocessed_lips"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "outputs": [],
   "source": [
    "def interpolate_and_crop(video, landmarks_folder, cropped_save_folder):\n",
    "    assert os.path.isfile(video), \"File does not exist. Path input: {}\".format(video)\n",
    "    dir, file = os.path.split(video)\n",
    "    part, which_folder = os.path.split(dir)\n",
    "    otherpart, word = os.path.split(part)\n",
    "    npz_filename = file[:-4] + \".npz\"\n",
    "\n",
    "    #Get Landmarks path and check that file exists\n",
    "    current_landmarks = os.path.join(landmarks_folder, word, which_folder, npz_filename)\n",
    "    assert os.path.isfile(current_landmarks), \"File does not exist. Path input: {}\".format(current_landmarks)\n",
    "    #Open Landmarks, interpolate missing\n",
    "    oval_landmarks, lips_landmarks = interpolate_oval_and_face(current_landmarks)\n",
    "    if oval_landmarks:\n",
    "        #Create save location for cropped video and transformed lips landmarks\n",
    "        output_save_video = os.path.join(cropped_save_folder, word, which_folder, file)\n",
    "        output_save_video_array_path = os.path.join(cropped_save_folder, word, which_folder, npz_filename)\n",
    "        output_save_lips_points = os.path.join(lips_folder, word, which_folder, npz_filename)\n",
    "\n",
    "        transformed_lips, output_save_video_as_array = crop_and_return_lip_landmarks(video, output_save_video, oval_landmarks, lips_landmarks)\n",
    "        save2npz(output_save_lips_points, data=transformed_lips)\n",
    "        save2npz(output_save_video_array_path, data= output_save_video_as_array)\n",
    "    else:\n",
    "        print(\"No Landmarks in any frame for {}\".format(video))"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "outputs": [],
   "source": [
    "lrw_path = '/media/taylorpap/1TBM2/DatasetML/lipread_mp4'\n",
    "landmarks_path = '/home/taylorpap/Bootcamp/LANDMARKS'\n",
    "which_folder = 'test'\n",
    "cropped_save_loc = '/home/taylorpap/Bootcamp/CroppedLRW'"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "outputs": [],
   "source": [
    "def multiprocess_cropping(lrw_path, landmarks_path, cropped_save_loc, word='*'):\n",
    "    videos = glob.glob(os.path.join(lrw_path, word, which_folder, '*.mp4'))\n",
    "    l= len(videos)\n",
    "    with tqdm(total = l) as pbar:\n",
    "        with concurrent.futures.ThreadPoolExecutor(max_workers=12) as executor:\n",
    "            futures = [executor.submit(interpolate_and_crop, video, landmarks_path, cropped_save_loc) for video in videos]\n",
    "            for future in concurrent.futures.as_completed(futures):\n",
    "                pbar.update(1)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "outputs": [],
   "source": [
    "#MULTIPROCESS\n",
    "#multiprocess_cropping(lrw_path, landmarks_path, cropped_save_loc)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "outputs": [],
   "source": [
    "#SINGLE PROCESS\n",
    "\n",
    "#videos = glob.glob(os.path.join(lrw_path, '*', which_folder, '*.mp4'))\n",
    "#for video in tqdm(videos):\n",
    "#    interpolate_and_crop(video, landmarks_path, cropped_save_loc)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "outputs": [],
   "source": [
    "#example = np.load('/home/taylorpap/Bootcamp/LANDMARKS/ABUSE/test/ABUSE_00027.npz', allow_pickle=True)['data']\n",
    "#print(example)\n",
    "#for each_frame in example[2:4]:\n",
    "#    print(each_frame)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "outputs": [],
   "source": [
    "#interpolate_and_crop('/media/taylorpap/1TBM2/DatasetML/lipread_mp4/ABOUT/test/ABOUT_00001.mp4', landmarks_path, cropped_save_loc)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "outputs": [],
   "source": [
    "temp_words_list = ['ABSOLUTELY', 'BUDGET', 'EVERYONE', 'HOUSE', 'MILITARY', 'PUBLIC', 'RESULT', 'SIGNIFICANT', 'WEATHER']\n",
    "which_folder = 'val'"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "outputs": [],
   "source": [
    "#for testing_words in temp_words_list:\n",
    "#   multiprocess_cropping(lrw_path, landmarks_path, cropped_save_loc, word=testing_words)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "outputs": [],
   "source": [
    "#['BUDGET', 'HOUSE', 'MILITARY', 'PUBLIC', 'RESULT']"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "outputs": [],
   "source": [
    "#MULTIPROCESS\n",
    "#which_folder = 'val'\n",
    "#multiprocess_cropping(lrw_path, landmarks_path, cropped_save_loc)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "outputs": [],
   "source": [
    "def get_wordslist_from_txt_file(file_path):\n",
    "    with open(file_path) as file:\n",
    "        word_list = file.readlines()\n",
    "        word_list = [item.rstrip() for item in word_list]\n",
    "    return word_list"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "outputs": [],
   "source": [
    "words_list_file = '/home/taylorpap/Bootcamp/wordlist.txt'\n",
    "words_list = get_wordslist_from_txt_file(words_list_file)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Current Word: SMALL\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 1000/1000 [00:25<00:00, 38.80it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Current Word: SOCIAL\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 1000/1000 [00:25<00:00, 39.56it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Current Word: SOMEONE\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 915/915 [00:23<00:00, 39.01it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Current Word: SOMETHING\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 1000/1000 [00:25<00:00, 38.62it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Current Word: SOUTH\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 1000/1000 [00:27<00:00, 36.94it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Current Word: SOUTHERN\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 901/901 [00:24<00:00, 37.11it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Current Word: SPEAKING\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 1000/1000 [00:27<00:00, 36.92it/s]\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n",
      "Exception ignored in: <function ZipFile.__del__ at 0x7f1b0bad93f0>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1808, in __del__\n",
      "    self.close()\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1830, in close\n",
      "    self._fpclose(fp)\n",
      "  File \"/home/taylorpap/anaconda3/envs/projectenv/lib/python3.10/zipfile.py\", line 1930, in _fpclose\n",
      "    fp.close()\n",
      "OSError: [Errno 28] No space left on device\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Current Word: SPECIAL\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 1000/1000 [00:23<00:00, 41.91it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Current Word: SPEECH\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 1000/1000 [00:23<00:00, 43.32it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Current Word: SPEND\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 834/834 [00:18<00:00, 44.35it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Current Word: SPENDING\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 1000/1000 [00:23<00:00, 42.69it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Current Word: SPENT\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 87%|████████▋ | 771/887 [00:16<00:02, 40.70it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "No Landmarks in any frame for /media/taylorpap/1TBM2/DatasetML/lipread_mp4/SPENT/train/SPENT_00359.mp4\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 887/887 [00:19<00:00, 45.80it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Current Word: STAFF\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 1000/1000 [00:22<00:00, 43.79it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Current Word: STAGE\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 948/948 [00:21<00:00, 43.98it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Current Word: STAND\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 10%|▉         | 96/1000 [00:22<03:33,  4.23it/s]\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001B[0;31m---------------------------------------------------------------------------\u001B[0m",
      "\u001B[0;31mKeyboardInterrupt\u001B[0m                         Traceback (most recent call last)",
      "Input \u001B[0;32mIn [32]\u001B[0m, in \u001B[0;36m<cell line: 5>\u001B[0;34m()\u001B[0m\n\u001B[1;32m      6\u001B[0m \u001B[38;5;28;01mfor\u001B[39;00m temp_word \u001B[38;5;129;01min\u001B[39;00m temp_words_list:\n\u001B[1;32m      7\u001B[0m     \u001B[38;5;28mprint\u001B[39m(\u001B[38;5;124m\"\u001B[39m\u001B[38;5;124mCurrent Word: \u001B[39m\u001B[38;5;132;01m{}\u001B[39;00m\u001B[38;5;124m\"\u001B[39m\u001B[38;5;241m.\u001B[39mformat(temp_word))\n\u001B[0;32m----> 8\u001B[0m     \u001B[43mmultiprocess_cropping\u001B[49m\u001B[43m(\u001B[49m\u001B[43mlrw_path\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43mlandmarks_path\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43mcropped_save_loc\u001B[49m\u001B[43m,\u001B[49m\u001B[43m \u001B[49m\u001B[43mword\u001B[49m\u001B[38;5;241;43m=\u001B[39;49m\u001B[43mtemp_word\u001B[49m\u001B[43m)\u001B[49m\n",
      "Input \u001B[0;32mIn [15]\u001B[0m, in \u001B[0;36mmultiprocess_cropping\u001B[0;34m(lrw_path, landmarks_path, cropped_save_loc, word)\u001B[0m\n\u001B[1;32m      5\u001B[0m \u001B[38;5;28;01mwith\u001B[39;00m concurrent\u001B[38;5;241m.\u001B[39mfutures\u001B[38;5;241m.\u001B[39mThreadPoolExecutor(max_workers\u001B[38;5;241m=\u001B[39m\u001B[38;5;241m12\u001B[39m) \u001B[38;5;28;01mas\u001B[39;00m executor:\n\u001B[1;32m      6\u001B[0m     futures \u001B[38;5;241m=\u001B[39m [executor\u001B[38;5;241m.\u001B[39msubmit(interpolate_and_crop, video, landmarks_path, cropped_save_loc) \u001B[38;5;28;01mfor\u001B[39;00m video \u001B[38;5;129;01min\u001B[39;00m videos]\n\u001B[0;32m----> 7\u001B[0m     \u001B[38;5;28;01mfor\u001B[39;00m future \u001B[38;5;129;01min\u001B[39;00m concurrent\u001B[38;5;241m.\u001B[39mfutures\u001B[38;5;241m.\u001B[39mas_completed(futures):\n\u001B[1;32m      8\u001B[0m         pbar\u001B[38;5;241m.\u001B[39mupdate(\u001B[38;5;241m1\u001B[39m)\n",
      "File \u001B[0;32m~/anaconda3/envs/projectenv/lib/python3.10/concurrent/futures/_base.py:245\u001B[0m, in \u001B[0;36mas_completed\u001B[0;34m(fs, timeout)\u001B[0m\n\u001B[1;32m    240\u001B[0m     \u001B[38;5;28;01mif\u001B[39;00m wait_timeout \u001B[38;5;241m<\u001B[39m \u001B[38;5;241m0\u001B[39m:\n\u001B[1;32m    241\u001B[0m         \u001B[38;5;28;01mraise\u001B[39;00m \u001B[38;5;167;01mTimeoutError\u001B[39;00m(\n\u001B[1;32m    242\u001B[0m                 \u001B[38;5;124m'\u001B[39m\u001B[38;5;132;01m%d\u001B[39;00m\u001B[38;5;124m (of \u001B[39m\u001B[38;5;132;01m%d\u001B[39;00m\u001B[38;5;124m) futures unfinished\u001B[39m\u001B[38;5;124m'\u001B[39m \u001B[38;5;241m%\u001B[39m (\n\u001B[1;32m    243\u001B[0m                 \u001B[38;5;28mlen\u001B[39m(pending), total_futures))\n\u001B[0;32m--> 245\u001B[0m \u001B[43mwaiter\u001B[49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43mevent\u001B[49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43mwait\u001B[49m\u001B[43m(\u001B[49m\u001B[43mwait_timeout\u001B[49m\u001B[43m)\u001B[49m\n\u001B[1;32m    247\u001B[0m \u001B[38;5;28;01mwith\u001B[39;00m waiter\u001B[38;5;241m.\u001B[39mlock:\n\u001B[1;32m    248\u001B[0m     finished \u001B[38;5;241m=\u001B[39m waiter\u001B[38;5;241m.\u001B[39mfinished_futures\n",
      "File \u001B[0;32m~/anaconda3/envs/projectenv/lib/python3.10/threading.py:600\u001B[0m, in \u001B[0;36mEvent.wait\u001B[0;34m(self, timeout)\u001B[0m\n\u001B[1;32m    598\u001B[0m signaled \u001B[38;5;241m=\u001B[39m \u001B[38;5;28mself\u001B[39m\u001B[38;5;241m.\u001B[39m_flag\n\u001B[1;32m    599\u001B[0m \u001B[38;5;28;01mif\u001B[39;00m \u001B[38;5;129;01mnot\u001B[39;00m signaled:\n\u001B[0;32m--> 600\u001B[0m     signaled \u001B[38;5;241m=\u001B[39m \u001B[38;5;28;43mself\u001B[39;49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43m_cond\u001B[49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43mwait\u001B[49m\u001B[43m(\u001B[49m\u001B[43mtimeout\u001B[49m\u001B[43m)\u001B[49m\n\u001B[1;32m    601\u001B[0m \u001B[38;5;28;01mreturn\u001B[39;00m signaled\n",
      "File \u001B[0;32m~/anaconda3/envs/projectenv/lib/python3.10/threading.py:320\u001B[0m, in \u001B[0;36mCondition.wait\u001B[0;34m(self, timeout)\u001B[0m\n\u001B[1;32m    318\u001B[0m \u001B[38;5;28;01mtry\u001B[39;00m:    \u001B[38;5;66;03m# restore state no matter what (e.g., KeyboardInterrupt)\u001B[39;00m\n\u001B[1;32m    319\u001B[0m     \u001B[38;5;28;01mif\u001B[39;00m timeout \u001B[38;5;129;01mis\u001B[39;00m \u001B[38;5;28;01mNone\u001B[39;00m:\n\u001B[0;32m--> 320\u001B[0m         \u001B[43mwaiter\u001B[49m\u001B[38;5;241;43m.\u001B[39;49m\u001B[43macquire\u001B[49m\u001B[43m(\u001B[49m\u001B[43m)\u001B[49m\n\u001B[1;32m    321\u001B[0m         gotit \u001B[38;5;241m=\u001B[39m \u001B[38;5;28;01mTrue\u001B[39;00m\n\u001B[1;32m    322\u001B[0m     \u001B[38;5;28;01melse\u001B[39;00m:\n",
      "\u001B[0;31mKeyboardInterrupt\u001B[0m: "
     ]
    }
   ],
   "source": [
    "which_folder = 'train'\n",
    "chunk_size=10\n",
    "chunked_words_list = [words_list[f:f+chunk_size] for f in range(0, len(words_list), chunk_size)]\n",
    "temp_words_list_outer = chunked_words_list[40:45]\n",
    "for temp_words_list in temp_words_list_outer:\n",
    "    for temp_word in temp_words_list:\n",
    "        print(\"Current Word: {}\".format(temp_word))\n",
    "        multiprocess_cropping(lrw_path, landmarks_path, cropped_save_loc, word=temp_word)"
   ],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "outputs": [],
   "source": [],
   "metadata": {
    "collapsed": false,
    "pycharm": {
     "name": "#%%\n"
    }
   }
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}